- hosts: localhost
  vars_prompt:
    - name: profile
      prompt: What is your profile? ('personal' or 'work')
      private: false
  pre_tasks:
    - name: Update Apt
      become: true
      ansible.builtin.package:
        update_cache: yes
        upgrade: yes
  tasks:
    - import_tasks: tasks/nix.yml
    - import_tasks: tasks/neovim.yml
    - import_tasks: tasks/home-manager.yml
