#! /bin/bash

alias ....='cd ../../..'
alias ...='cd ../..'
alias ..='cd ..'
alias gs="git status"
alias ls="ls --color=auto"
alias mv="mv -i"
alias rm="rm -i"
alias v='lvim'
alias vim='lvim'
alias aws-exec="aws-vault exec my-aws-account --"
alias lg="lazygit"
alias ibrew="arch -x86_64 /usr/local/bin/brew"
alias dot='/usr/bin/git --git-dir=$HOME/.dotfiles/ --work-tree=$HOME'
