hup:
	home-manager switch

up:
	nixos-rebuild switch

link:
	sudo ln -s ~/.config/nixos/configuration.nix /etc/nixos/configuration.nix
	sudo ln -s ~/.config/nixos/hardware-configuration.nix /etc/nixos/hardware-configuration.nix
