#! /bin/bash

# add to path
export PATH=$PATH:~/.local/bin
export PATH=$PATH~/.local/private_bin:$PATH
export PATH=/opt/homebrew/bin:$PATH
export PATH=$PATH:~/.cargo/bin
export PATH="$HOME/.rbenv/bin:$PATH"
export PATH=$PATH:$HOME/.tfenv/bin

[ -s rbenv ] && eval "$(rbenv init -)"


# == NVM ==

export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion
