name: CI

on:
  push:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Run a one-line script
        run: echo Hello, world!

      - name: ansible
      - uses: tomasnorre/ansible-cli-client@0.0.2
        with:
          command: ansible-playbook ~/.config/ansible/local.yml --ask-become-pass
